-ifndef(EGPGME_INCLUDED).
-define(EGPGME_INCLUDED, true).

-opaque egpgme_context() :: binary().
-opaque egpgme_data() :: binary().
-opaque egpgme_key() :: binary().

-define(EGPGME_PROTOCOL_OpenPGP, 0).
-define(EGPGME_PROTOCOL_CMS, 1).
-define(EGPGME_PROTOCOL_GPGCONF, 2).
-define(EGPGME_PROTOCOL_ASSUAN, 3).
-define(EGPGME_PROTOCOL_G13, 4).
-define(EGPGME_PROTOCOL_UISERVER, 5).
-define(EGPGME_PROTOCOL_DEFAULT, 254).
-define(EGPGME_PROTOCOL_UNKNOWN, 255).

-define(EGPGME_PK_RSA, 1).
-define(EGPGME_PK_RSA_E, 2).
-define(EGPGME_PK_RSA_S, 3).
-define(EGPGME_PK_ELG_E, 16).
-define(EGPGME_PK_DSA, 17).
-define(EGPGME_PK_ELG, 20).
-define(EGPGME_PK_ECDSA, 301).
-define(EGPGME_PK_ECDH, 302).

-define(EGPGME_MD_NONE, 0).
-define(EGPGME_MD_MD5, 1).
-define(EGPGME_MD_SHA1, 2).
-define(EGPGME_MD_RMD160, 3).
-define(EGPGME_MD_MD2, 5).
-define(EGPGME_MD_TIGER, 6).
-define(EGPGME_MD_HAVAL, 7).
-define(EGPGME_MD_SHA256, 8).
-define(EGPGME_MD_SHA384, 9).
-define(EGPGME_MD_SHA512, 10).
-define(EGPGME_MD_MD4, 301).
-define(EGPGME_MD_CRC32, 302).
-define(EGPGME_MD_CRC32_RFC1510, 303).
-define(EGPGME_MD_CRC24_RFC2440, 304).

-define(EGPGME_KEYLIST_MODE_LOCAL, 1).
-define(EGPGME_KEYLIST_MODE_EXTERN, 2).
-define(EGPGME_KEYLIST_MODE_SIGS, 4).
-define(EGPGME_KEYLIST_MODE_SIG_NOTATIONS, 8).
-define(EGPGME_KEYLIST_MODE_EPHEMERAL, 128).
-define(EGPGME_KEYLIST_MODE_VALIDATE, 256).

-define(EGPGME_EXPORT_MODE_EXTERN, 2).
-define(EGPGME_EXPORT_MODE_MINIMAL, 4).

-define(EGPGME_INCLUDE_CERTS_DEFAULT, -256).

-define(EGPGME_SIG_NOTATION_HUMAN_READABLE, 1).
-define(EGPGME_SIG_NOTATION_CRITICAL, 2).

-define(EGPGME_DATA_ENCODING_NONE, 0).
-define(EGPGME_DATA_ENCODING_BINARY, 1).
-define(EGPGME_DATA_ENCODING_BASE64, 2).
-define(EGPGME_DATA_ENCODING_ARMOR, 3).
-define(EGPGME_DATA_ENCODING_URL, 4).
-define(EGPGME_DATA_ENCODING_URLESC, 5).
-define(EGPGME_DATA_ENCODING_URL0, 6).

-define(EGPGME_DATA_SEEK_SET, 0).
-define(EGPGME_DATA_SEEK_CUR, 1).
-define(EGPGME_DATA_SEEK_END, 2).

-define(EGPGME_ENCRYPT_ALWAYS_TRUST, 1).
-define(EGPGME_ENCRYPT_NO_ENCRYPT_TO, 2).
-define(EGPGME_ENCRYPT_PREPARE, 4).
-define(EGPGME_ENCRYPT_EXPECT_SIGN, 8).

-define(EGPGME_SIGSUM_VALID, 16#0001).
-define(EGPGME_SIGSUM_GREEN, 16#0002).
-define(EGPGME_SIGSUM_RED, 16#0004).
-define(EGPGME_SIGSUM_KEY_REVOKED, 16#0010).
-define(EGPGME_SIGSUM_KEY_EXPIRED, 16#0020).
-define(EGPGME_SIGSUM_SIG_EXPIRED, 16#0040).
-define(EGPGME_SIGSUM_KEY_MISSING, 16#0080).
-define(EGPGME_SIGSUM_CRL_MISSING, 16#0100).
-define(EGPGME_SIGSUM_CRL_TOO_OLD, 16#0200).
-define(EGPGME_SIGSUM_BAD_POLICY, 16#0400).
-define(EGPGME_SIGSUM_SYS_ERROR, 16#0800).

-define(EGPGME_IMPORT_UID, 2).
-define(EGPGME_IMPORT_SIG, 4).
-define(EGPGME_IMPORT_SUBKEY, 8).
-define(EGPGME_IMPORT_SECRET, 16).

-endif.
